//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landers.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConversionResult
    {
        public decimal Id { get; set; }
        public Nullable<decimal> TestId { get; set; }
        public Nullable<int> Impression { get; set; }
        public Nullable<decimal> VariationId { get; set; }
        public string SubmitUrl { get; set; }
        public string Referrer { get; set; }
        public Nullable<decimal> LeadId { get; set; }
    }
}
