//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landers.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Replacement
    {
        public decimal Id { get; set; }
        public Nullable<decimal> VariationId { get; set; }
        public string Find { get; set; }
        public string Replace { get; set; }
        public bool Enabled { get; set; }
    }
}
