//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landers.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variation
    {
        public decimal Id { get; set; }
        public Nullable<decimal> TestId { get; set; }
        public string Variation1 { get; set; }
        public string Description { get; set; }
        public string ViewName { get; set; }
        public bool DefaultView { get; set; }
        public bool Base { get; set; }
        public decimal Template { get; set; }
        public decimal Impressions { get; set; }
    }
}
